/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.librarymanagement;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class HomePageScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePageScreen.class.getName());

    /**
     * Creates new form HomePageScreen
     */
    public HomePageScreen() {
        initComponents();
         Students page = new Students();
        dashboard.setLayout(new BorderLayout());
        dashboard.removeAll();
        dashboard.add(page,BorderLayout.CENTER);
        dashboard.revalidate();
        dashboard.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addstudentPanel = new javax.swing.JPanel();
        addstudentLabel = new javax.swing.JLabel();
        addbooksPanel = new javax.swing.JPanel();
        addbooksLabel = new javax.swing.JLabel();
        studentreportPanel = new javax.swing.JPanel();
        studentreportLabel = new javax.swing.JLabel();
        bookreportPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bookreportLabel = new javax.swing.JLabel();
        bookissuePanel = new javax.swing.JPanel();
        bookissueLabel = new javax.swing.JLabel();
        returnbookPanel = new javax.swing.JPanel();
        returnbookLabel = new javax.swing.JLabel();
        viewBookPanel = new javax.swing.JPanel();
        textBookView = new javax.swing.JLabel();
        isseuBookViewPanel = new javax.swing.JPanel();
        textIssueBookView = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("          LIBRARY DATA RECORD");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 280, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 60));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addstudentPanel.setBackground(new java.awt.Color(204, 204, 204));
        addstudentPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        addstudentPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addstudentPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addstudentPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addstudentPanelMouseExited(evt);
            }
        });
        addstudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addstudentLabel.setText("NEW STUDENT ");
        addstudentPanel.add(addstudentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel3.add(addstudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        addbooksPanel.setBackground(new java.awt.Color(204, 204, 204));
        addbooksPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        addbooksPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbooksPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addbooksPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addbooksPanelMouseExited(evt);
            }
        });
        addbooksPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addbooksLabel.setText("NEWBOOKS");
        addbooksPanel.add(addbooksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel3.add(addbooksPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, 30));

        studentreportPanel.setBackground(new java.awt.Color(204, 204, 204));
        studentreportPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        studentreportPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentreportPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentreportPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentreportPanelMouseExited(evt);
            }
        });
        studentreportPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentreportLabel.setText("STUDENT REPORT");
        studentreportPanel.add(studentreportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 101, -1));

        jPanel3.add(studentreportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, 30));

        bookreportPanel.setBackground(new java.awt.Color(204, 204, 204));
        bookreportPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        bookreportPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookreportPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookreportPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookreportPanelMouseExited(evt);
            }
        });
        bookreportPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bookreportPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 7, -1, -1));

        bookreportLabel.setText("STUDENT VIEW");
        bookreportPanel.add(bookreportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel3.add(bookreportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 30));

        bookissuePanel.setBackground(new java.awt.Color(204, 204, 204));
        bookissuePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        bookissuePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookissuePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookissuePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookissuePanelMouseExited(evt);
            }
        });
        bookissuePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookissueLabel.setText("ISSUE BOOK");
        bookissuePanel.add(bookissueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 78, 20));

        jPanel3.add(bookissuePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 170, 30));

        returnbookPanel.setBackground(new java.awt.Color(204, 204, 204));
        returnbookPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        returnbookPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnbookPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnbookPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnbookPanelMouseExited(evt);
            }
        });
        returnbookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnbookLabel.setText("RETURN BOOK");
        returnbookPanel.add(returnbookLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel3.add(returnbookPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, 30));

        viewBookPanel.setBackground(new java.awt.Color(204, 204, 204));
        viewBookPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        viewBookPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBookPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewBookPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewBookPanelMouseExited(evt);
            }
        });
        viewBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textBookView.setText("BOOK VIEW");
        viewBookPanel.add(textBookView, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, -1));

        jPanel3.add(viewBookPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, 30));

        isseuBookViewPanel.setBackground(new java.awt.Color(204, 204, 204));
        isseuBookViewPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        isseuBookViewPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isseuBookViewPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isseuBookViewPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isseuBookViewPanelMouseExited(evt);
            }
        });
        isseuBookViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textIssueBookView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textIssueBookView.setText("ISSUE BOOK VIEW");
        isseuBookViewPanel.add(textIssueBookView, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, -1));

        jPanel3.add(isseuBookViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 170, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, 420));

        dashboard.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 740, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addstudentPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addstudentPanelMouseClicked
        // TODO add your handling code here
         Students page = new Students();
        dashboard.setLayout(new BorderLayout());
        dashboard.removeAll();
        dashboard.add(page,BorderLayout.CENTER);
        dashboard.revalidate();
        dashboard.repaint();
        
    }//GEN-LAST:event_addstudentPanelMouseClicked

    private void addstudentPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addstudentPanelMouseEntered
        // TODO add your handling code here:
         Color color = new Color(255, 204, 204);
        addstudentPanel.setBackground(color);
        addstudentLabel.setForeground(color.white);
    }//GEN-LAST:event_addstudentPanelMouseEntered

    private void addstudentPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addstudentPanelMouseExited
        // TODO add your handling code here:
        
        
         Color color = new Color(204, 204, 204);
        addstudentLabel.setForeground(color.BLACK);
        addstudentPanel.setBackground(color);
    }//GEN-LAST:event_addstudentPanelMouseExited

    private void addbooksPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbooksPanelMouseClicked
        // TODO add your handling code here:
         Addbooks page = new Addbooks();
        dashboard.setLayout(new BorderLayout());
        dashboard.removeAll();
        dashboard.add(page,BorderLayout.CENTER);
        dashboard.revalidate();
        dashboard.repaint();
    }//GEN-LAST:event_addbooksPanelMouseClicked

    private void addbooksPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbooksPanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addbooksPanelMouseEntered

    private void addbooksPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbooksPanelMouseExited
        // TODO add your handling code here:
         Color color = new Color(204, 204, 204);
        addbooksLabel.setForeground(color.BLACK);
        addbooksPanel.setBackground(color);
    }//GEN-LAST:event_addbooksPanelMouseExited

    private void studentreportPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentreportPanelMouseClicked
        // TODO add your handling code here:
          StudentReport page = new StudentReport();
        dashboard.setLayout(new BorderLayout());
        dashboard.removeAll();
        dashboard.add(page,BorderLayout.CENTER);
        dashboard.revalidate();
        dashboard.repaint();
        
    }//GEN-LAST:event_studentreportPanelMouseClicked

    private void studentreportPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentreportPanelMouseEntered
        // TODO add your handling code here:
         Color color = new Color(255, 204, 204);
        studentreportPanel.setBackground(color);
        studentreportLabel.setForeground(color.white);
    }//GEN-LAST:event_studentreportPanelMouseEntered

    private void studentreportPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentreportPanelMouseExited
        // TODO add your handling code here:
        Color color = new Color(204, 204, 204);
        studentreportLabel.setForeground(color.BLACK);
        studentreportPanel.setBackground(color);
    }//GEN-LAST:event_studentreportPanelMouseExited

    private void bookreportPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreportPanelMouseClicked
        // TODO add your handling code here:
        StudentTable page = new StudentTable();
        dashboard.setLayout(new BorderLayout());
        dashboard.removeAll();
        dashboard.add(page,BorderLayout.CENTER);
        dashboard.revalidate();
        dashboard.repaint();
    }//GEN-LAST:event_bookreportPanelMouseClicked

    private void bookreportPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreportPanelMouseEntered
        // TODO add your handling code here:
        Color color = new Color(255, 204, 204);
        bookreportPanel.setBackground(color);
        bookreportLabel.setForeground(color.white);
    }//GEN-LAST:event_bookreportPanelMouseEntered

    private void bookreportPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookreportPanelMouseExited
        // TODO add your handling code here:
        Color color = new Color(204, 204, 204);
        bookreportLabel.setForeground(color.BLACK);
        bookreportPanel.setBackground(color);
    }//GEN-LAST:event_bookreportPanelMouseExited

    private void bookissuePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookissuePanelMouseClicked
        // TODO add your handling code here:
        IssueBooks page = new IssueBooks();
        dashboard.setLayout(new BorderLayout());
        dashboard.removeAll();
        dashboard.add(page, BorderLayout.CENTER);
        dashboard.revalidate();
        dashboard.repaint();
    }//GEN-LAST:event_bookissuePanelMouseClicked

    private void bookissuePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookissuePanelMouseEntered
        // TODO add your handling code here:
         Color color = new Color(255, 204, 204);
        bookissuePanel.setBackground(color);
        bookissueLabel.setForeground(color.white);
    }//GEN-LAST:event_bookissuePanelMouseEntered

    private void bookissuePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookissuePanelMouseExited
        // TODO add your handling code here:
          Color color = new Color(204, 204, 204);
        bookissueLabel.setForeground(color.BLACK);
        bookissuePanel.setBackground(color);
        
    }//GEN-LAST:event_bookissuePanelMouseExited

    private void returnbookPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnbookPanelMouseClicked
        // TODO add your handling code here:
         // Color color = new Color(204, 204, 204);
       // bookissueLabel.setForeground(color.BLACK);
       // bookissuePanel.setBackground(color);
       Returnbooks page = new Returnbooks();
        dashboard.setLayout(new BorderLayout());
        dashboard.removeAll();
        dashboard.add(page, BorderLayout.CENTER);
        dashboard.revalidate();
        dashboard.repaint();
    }//GEN-LAST:event_returnbookPanelMouseClicked

    private void returnbookPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnbookPanelMouseEntered
        // TODO add your handling code here:
          Color color = new Color(255, 204, 204);
        returnbookPanel.setBackground(color);
        returnbookLabel.setForeground(color.white);
    }//GEN-LAST:event_returnbookPanelMouseEntered

    private void returnbookPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnbookPanelMouseExited
        // TODO add your handling code here:
         Color color = new Color(204, 204, 204);
        returnbookLabel.setForeground(color.BLACK);
        returnbookPanel.setBackground(color);
    }//GEN-LAST:event_returnbookPanelMouseExited

    private void viewBookPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBookPanelMouseClicked
        // TODO add your handling code here:
        BookTable page= new BookTable();
        dashboard.setLayout(new BorderLayout());
        dashboard.removeAll();
        dashboard.add(page,BorderLayout.CENTER);
        dashboard.revalidate();
        dashboard.repaint();
    }//GEN-LAST:event_viewBookPanelMouseClicked

    private void viewBookPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBookPanelMouseEntered
        // TODO add your handling code here:
  Color color = new Color(255, 204, 204);
        viewBookPanel.setBackground(color);
        textBookView.setForeground(color.white);        
    }//GEN-LAST:event_viewBookPanelMouseEntered

    private void viewBookPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBookPanelMouseExited
        // TODO add your handling code here:
         Color color = new Color(204, 204, 204);
     textBookView.setForeground(color.BLACK);
        viewBookPanel.setBackground(color);
    }//GEN-LAST:event_viewBookPanelMouseExited

    private void isseuBookViewPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isseuBookViewPanelMouseClicked
        // TODO add your handling code here:
          IssueBookView page= new IssueBookView();
        dashboard.setLayout(new BorderLayout());
        dashboard.removeAll();
        dashboard.add(page,BorderLayout.CENTER);
        dashboard.revalidate();
        dashboard.repaint();
    }//GEN-LAST:event_isseuBookViewPanelMouseClicked

    private void isseuBookViewPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isseuBookViewPanelMouseEntered
        // TODO add your handling code here:
        Color color = new Color(255, 204, 204);
        isseuBookViewPanel.setBackground(color);
        textIssueBookView.setForeground(color.white); 
    }//GEN-LAST:event_isseuBookViewPanelMouseEntered

    private void isseuBookViewPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isseuBookViewPanelMouseExited
        // TODO add your handling code here:
          Color color = new Color(204, 204, 204);
     textIssueBookView.setForeground(color.BLACK);
        isseuBookViewPanel.setBackground(color);
    }//GEN-LAST:event_isseuBookViewPanelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomePageScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addbooksLabel;
    private javax.swing.JPanel addbooksPanel;
    private javax.swing.JLabel addstudentLabel;
    private javax.swing.JPanel addstudentPanel;
    private javax.swing.JLabel bookissueLabel;
    private javax.swing.JPanel bookissuePanel;
    private javax.swing.JLabel bookreportLabel;
    private javax.swing.JPanel bookreportPanel;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel isseuBookViewPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel returnbookLabel;
    private javax.swing.JPanel returnbookPanel;
    private javax.swing.JLabel studentreportLabel;
    private javax.swing.JPanel studentreportPanel;
    private javax.swing.JLabel textBookView;
    private javax.swing.JLabel textIssueBookView;
    private javax.swing.JPanel viewBookPanel;
    // End of variables declaration//GEN-END:variables
}
