/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.librarymanagement;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Malhotra Computer
 */
public class IssueBooks extends javax.swing.JPanel {
        ArrayList<IssueModel> formList = new ArrayList<>();
    
     ArrayList<StudentModel> studentList = new ArrayList<>();
        ArrayList<BookModel> bookList = new ArrayList<>();
SingletonClass conn = SingletonClass.getInstance();
    /**
     * Creates new form IssueBooks
     */
    public IssueBooks() {
        initComponents();
        getaddbooks();
        getStudent();
    }
     void getaddbooks(){
       
         String getData =" SELECT * FROM  addbooks";    
         DefaultComboBoxModel<String> combo =new DefaultComboBoxModel();

         try {
               Statement statement = conn.connection.createStatement();
              ResultSet result =  statement.executeQuery(getData);
             
              
              while(result.next()){
                 BookModel model = new BookModel(
                         result.getInt("id"), 
                         result.getString("name"),
                         result. getString("publisher"),
                         result. getInt("price"),
                         result.getString("publisheryear"));
                 bookList.add(model);
                 combo.addElement(model.getBookName()); 
              }
              bookMenu.setModel(combo);
              } catch (SQLException ex){
                  System.getLogger(StudentTable.class. getName()).log(System.Logger.Level.ERROR,(String)null, ex);   
              }
    }
    void  getStudent(){
         String getData =" SELECT * FROM  studentinformation";    
         try {
              Statement statement = conn.connection.createStatement();
              ResultSet result =  statement.executeQuery(getData);
              DefaultComboBoxModel<String> model = new DefaultComboBoxModel();

              while(result.next()){
                StudentModel studentModel = new StudentModel(
                        result.getInt("id"),
                        result.getString("name"),
                        result.getString("branch"),
                        result. getString("fatherName"),
                        result. getString("contactNo"),
                        result.getString("collegeName"));
                studentList.add(studentModel);
                model.addElement(studentModel.getName());
              }
              studentMenu.setModel(model);
                } catch (SQLException ex){
                    System.getLogger(StudentTable.class. getName()).log(System.Logger.Level.ERROR,(String)null, ex);
                    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bookidLabel = new javax.swing.JLabel();
        studentidLabel = new javax.swing.JLabel();
        issuedateLabel = new javax.swing.JLabel();
        duedateLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        bookMenu = new javax.swing.JComboBox<>();
        studentMenu = new javax.swing.JComboBox<>();
        issueDate = new com.toedter.calendar.JDateChooser();
        dueDate = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ISSUE BOOKS INFORMATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(420, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 40));

        bookidLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        bookidLabel.setForeground(new java.awt.Color(255, 255, 255));
        bookidLabel.setText("Book Name");
        jPanel1.add(bookidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        studentidLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        studentidLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentidLabel.setText("Student Name");
        jPanel1.add(studentidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        issuedateLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        issuedateLabel.setForeground(new java.awt.Color(255, 255, 255));
        issuedateLabel.setText("ISSUE DATE ");
        jPanel1.add(issuedateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 110, -1));

        duedateLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        duedateLabel.setForeground(new java.awt.Color(255, 255, 255));
        duedateLabel.setText("DUE DATE");
        jPanel1.add(duedateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        bookMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(bookMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 160, -1));

        studentMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(studentMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 160, -1));
        jPanel1.add(issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 160, -1));
        jPanel1.add(dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
         if (issueDate.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please Select the Issue Date");
        }
        
        else if (dueDate.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please Select the Due Date");
        }else {
            try {
                int index = studentMenu.getSelectedIndex();
                StudentModel model = studentList.get(index);
                int studentId = model.getId();
                String studentName = model.getName();
                
                 int bookIndex = bookMenu.getSelectedIndex();
                BookModel bookModel = bookList.get(index);
                int bookId = bookModel.getId();
                String bookName = bookModel.getBookName();
                // Issue Date
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                String issueBookDate = sdf.format(issueDate.getDate());
                
                 // Issue Date
                SimpleDateFormat sdf1 = new SimpleDateFormat("dd-MM-yyyy");
                String dueBookDate = sdf1.format(dueDate.getDate());
                

                String issuebook = "INSERT INTO issuebook(studentId, bookName, studentName , issuedate, duedate) VALUES (?, ?, ?, ?, ? )";

                PreparedStatement ps2 = conn.connection.prepareCall(issuebook);

                ps2.setInt(1,studentId);
                ps2.setString(2, bookName);
                ps2.setString(3, studentName);
               // ps2.setInt(3,bookId);
                
                ps2.setString(4, issueBookDate);
                ps2.setString(5, dueBookDate);

                if (ps2.executeUpdate() > 0) {
                    System.out.println("Data Inserted Successfully");
                    JOptionPane.showMessageDialog(this, " BOOK ISSUED SUCCESSFUL");
                    //getissuebook();
                    // Optional: Clear fields

                    
                    // Optional: Navigate to another form
                    // new StudentForm().setVisible(true);
                    // dispose();
                }
            } catch ( SQLException ex) {
               System.out.println("Check Excepiton on Issue Book: "+ex); // Prints full SQL error details
            }
        }
       
    
    }//GEN-LAST:event_saveButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bookMenu;
    private javax.swing.JLabel bookidLabel;
    private com.toedter.calendar.JDateChooser dueDate;
    private javax.swing.JLabel duedateLabel;
    private javax.swing.JButton exitButton;
    private com.toedter.calendar.JDateChooser issueDate;
    private javax.swing.JLabel issuedateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> studentMenu;
    private javax.swing.JLabel studentidLabel;
    // End of variables declaration//GEN-END:variables

//    private void getissuebook() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

}
