/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.librarymanagement;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class IssueBookView extends javax.swing.JPanel {
 ArrayList<IssueModel> issueList = new ArrayList<>();
    SingletonClass conn = SingletonClass.getInstance();
//    int issueId = 0;
//    int bookId = 0;
     int Id = 0;
int issueId = 0;
    String studentName = "";
    String bookName = "";
    String issueDate = "";
    String DueDate = "";
    /**
     * Creates new form IssueBookView
     */
    public IssueBookView() {
        initComponents();
        getissuebook();
    }
     void getissuebook(){
        String header[] ={ "Id","BookName","StudentName", "IssueDate"," DueDate"};
         String getData =" SELECT * FROM  issuebook"; 
         try {
               Statement statement = conn.connection.createStatement();
              ResultSet result =  statement.executeQuery(getData);
              DefaultTableModel model =new DefaultTableModel(null, header);
              issueTable.setModel(model);
              model.setRowCount(0);
              while(result.next()){
                 issueList.add(new IssueModel( result.getInt("id"), result.getString("bookName"), result.getString("studentName") ,result.getString("issuedate"),result.getString("duedate")));
              }
              Object[] row =new Object[5];
              for (IssueModel item : issueList){


                   row[0]= item.getId();
                 
                  row[1] = item.getBookName();
                   row[2]= item.getstudentName();
                  row[3]= item.getissuedate();
                  row[4]= item.getduedate();
              
                  model.addRow(row);
              }
} catch (SQLException ex){
                  System.getLogger(ITable.class. getName()).log(System.Logger.Level.ERROR,(String)null, ex);
                  
              }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        issueTable = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 420));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Issue book view");

        issueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "BOOK NAME", "STUDENT NAME", "ISSUEDATE", "DUE DATE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        issueTable.setRowHeight(30);
        issueTable.setShowHorizontalLines(true);
        issueTable.getTableHeader().setReorderingAllowed(false);
        issueTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issueTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(issueTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void issueTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueTableMouseClicked
    int result = JOptionPane.showConfirmDialog(
    this, 
    "Are you sure you want to return the book?", 
    "Confirm Return", 
    JOptionPane.YES_NO_OPTION
);
        if (result == JOptionPane.YES_OPTION) {
          int selectedRow = issueTable.getSelectedRow();

      issueId = Integer.parseInt(issueTable.getValueAt(selectedRow, 0).toString());
System.out.println("IssueId: "+issueId);
String dueDateStr = issueTable.getValueAt(selectedRow, 4).toString();
String issueDateStr = issueTable.getValueAt(selectedRow, 3).toString();
  bookName = issueTable.getValueAt(selectedRow, 2).toString();
  studentName = issueTable.getValueAt(selectedRow, 1).toString();
  
  System.out.println("Check issueDate: "+issueDateStr);
    System.out.println("Check dueDateStr: "+dueDateStr);

      System.out.println("Check issueId: "+issueId);


System.out.println("bookName: "+bookName + "studentName"+studentName);

     try {
         SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
         Date dueDate = sdf.parse(dueDateStr);
         Date returnDate = new Date();
         int finePerDay = 10;
         double fine = 0;

         if (returnDate.after(dueDate)) {
         long diffMillis = returnDate.getTime() - dueDate.getTime();
        long daysLate = diffMillis / (1000 * 60 * 60 * 24);
        fine = (int) daysLate * finePerDay;
        System.out.println("Check Fine due date: "+ fine);
        ReturnIssueBook(fine,issueId,bookName,studentName,issueDateStr,dueDateStr);
        
        
}else{
         fine = 0;
         ReturnIssueBook(fine,issueId, bookName,studentName,issueDateStr,dueDateStr );
         System.out.println("Check Fine No due date: "+ fine);
         
         }
     } catch (ParseException ex) {
         System.out.println("Check Date ex "+ex);
     }
    
} else {
    // User canceled
    System.out.println("Return canceled.");
}                                         
    }//GEN-LAST:event_issueTableMouseClicked

void ReturnIssueBook(double fine, int issueId, String bookName, String studentName, String issueDateStr, String dueDateStr){
String checkReturnQuery = "SELECT * FROM returnbook WHERE issueId = ?";

   String returnbook = "INSERT INTO returnbook(issueId, StudentName, bookName ,issuedate, duedate,bookReturnDate, fine ) VALUES (?, ?, ?, ?, ?, ?, ?)";
   LocalDate today = LocalDate.now();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String dateString = today.format(formatter);

   try{
        PreparedStatement checkPs = conn.connection.prepareStatement(checkReturnQuery);
        checkPs.setInt(1, issueId);
        ResultSet rs = checkPs.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(this,"This book has already been returned.");
         //   System.out.println("This book has already been returned.");
            return; // Exit method early
        }

        // Step 2: Proceed to insert if not returned
       
       PreparedStatement ps = conn.connection.prepareCall(returnbook);
       ps.setInt(1,issueId);
       ps.setString(2, studentName);
        ps.setString(3, bookName);
         ps.setString(4, issueDateStr);
         ps.setString(5, dueDateStr);
         ps.setString(6, dateString);
         ps.setDouble(7, fine);
         if(ps.executeUpdate()>0){
            System.out.println("Inserted in Return Book");
         }
   
   }catch(SQLException exception){
    System.out.println("Check Return Book ex "+exception);
   }
   
   

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable issueTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
