/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.librarymanagement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Malhotra Computer
 */
public class Returnbooks extends javax.swing.JPanel {
    ArrayList<ReturnModel> returnList = new ArrayList<>();
    SingletonClass conn = SingletonClass.getInstance();
    
//SingletonClass conn = SingletonClass.getInstance();
    /**
     * Creates new form Returnbooks
     */
    public Returnbooks() {
        initComponents();
        getreturnbook();
    }
void getreturnbook(){
        String header[] ={ "Id", " issueId" ,"StudentName","BookName", "issuedate"," duedate", "bookReturnDate","fine"};
         String getData =" SELECT * FROM  returnbook"; 
          try {
               Statement statement = conn.connection.createStatement();
              ResultSet result =  statement.executeQuery(getData);
              DefaultTableModel model =new DefaultTableModel(null, header);
              returnbook.setModel(model);
              model.setRowCount(0);
              while(result.next()){
                 returnList.add(new ReturnModel( result.getInt("id"), result.getInt("issueId"), result.getString("studentName") , result.getString("bookName") ,result.getString("issuedate"), result.getString("duedate") , result.getString("bookReturnDate") ,result.getDouble("fine")));
              }
              Object[] row =new Object[8];
              for (ReturnModel item : returnList){


                   row[0]= item.getid();
                 row[1] = item.getissueID();
                  row[2]= item.getstudentName();
                  row[3]= item.getbookName();
                  row[4]= item.getissuedate();
                  row[5] = item.getduedate();
                  row[6]= item.getbookReturnDate();
                  row[7]= item.getfine();
                  
              
                  model.addRow(row);
              }
} catch (SQLException ex){
                  System.getLogger(ITable.class. getName()).log(System.Logger.Level.ERROR,(String)null, ex);
                  
              }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        returnbook = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("RETURN BOOK INFORMATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 60));

        returnbook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "issueId", "studentName", "bookName", "issuedate", "duedate", "bookreturnDate", "fine"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(returnbook);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 710, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable returnbook;
    // End of variables declaration//GEN-END:variables
}
