/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.librarymanagement;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Malhotra Computer
 */
public class Students extends javax.swing.JPanel {
    SingletonClass conn = SingletonClass.getInstance();

    /**
     * Creates new form Students
     */
    public Students() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        studentbranchLabel = new javax.swing.JLabel();
        studentfatherLabel = new javax.swing.JLabel();
        studentcontactLabel = new javax.swing.JLabel();
        collegenameLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        studentName = new javax.swing.JTextField();
        studentfatherTextField = new javax.swing.JTextField();
        studentcontactTextField = new javax.swing.JTextField();
        collegenameTextField = new javax.swing.JTextField();
        studentbranchLabel1 = new javax.swing.JLabel();
        studentbranchTextField1 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setText("STUDENT INFORMATION");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 333, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 50));

        studentbranchLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentbranchLabel.setForeground(new java.awt.Color(255, 255, 255));

        studentbranchLabel.setText("STUDENT ID");
        jPanel1.add(studentbranchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));
        studentbranchLabel.setText("Name");
        jPanel1.add(studentbranchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        studentfatherLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentfatherLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentfatherLabel.setText("FATHER'S NAME");
        jPanel1.add(studentfatherLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        studentcontactLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentcontactLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentcontactLabel.setText("CONTACT NO. ");
        jPanel1.add(studentcontactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        collegenameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        collegenameLabel.setForeground(new java.awt.Color(255, 255, 255));
        collegenameLabel.setText("COLLEGE NAME ");
        jPanel1.add(collegenameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        saveButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        studentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameActionPerformed(evt);
            }
        });
        jPanel1.add(studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 160, -1));

        studentfatherTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentfatherTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(studentfatherTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 160, -1));

        studentcontactTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentcontactTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(studentcontactTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 160, -1));

        collegenameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegenameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(collegenameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 160, -1));

        studentbranchLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentbranchLabel1.setForeground(new java.awt.Color(255, 255, 255));
        studentbranchLabel1.setText("BRANCH");
        jPanel1.add(studentbranchLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        studentbranchTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentbranchTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(studentbranchTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (studentName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ENTER YOUR STUDENT NAME");
        } else if (studentbranchTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ENTER YOUR BRANCH NAME");
        }

        else if (studentfatherTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ENTER YOUR FATHER NAME");
        } else if (studentcontactTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ENTER YOUR FATHER NAME");
        } else if (studentcontactTextField.getText().length() < 10) {
            JOptionPane.showMessageDialog(this, "MUST CONTAIN AT LEAST 10 DIGITS");
        } else if (!studentcontactTextField.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "CONTACT MUST CONTAIN ONLY DIGITS");
        } else if (collegenameTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ENTER YOUR COLLEGE NAME");
        }

        else {
            try {
                String student = "INSERT INTO studentinformation(name, branch, fatherName, contactNo, collegeName) VALUES (?, ?, ?, ?, ?)";

                PreparedStatement ps = conn.connection.prepareCall(student);

                ps.setString(1, studentName.getText());
                ps.setString(2, studentbranchTextField1.getText());
                ps.setString(3, studentfatherTextField.getText());
                ps.setString(4, studentcontactTextField.getText());
                ps.setString(5, collegenameTextField.getText());

                if (ps.executeUpdate() > 0) {
                    System.out.println("Data Inserted Successfully");
                    JOptionPane.showMessageDialog(this, "REGISTRATION SUCCESSFUL");

                    // Optional: Clear fields

                    studentName.setText("");
                    studentfatherTextField.setText("");
                    studentcontactTextField.setText("");
                    collegenameTextField.setText("");
                    // Optional: Navigate to another form
                    // new StudentForm().setVisible(true);

                    // dispose();
                }

            } catch (SQLException ex) {
                ex.printStackTrace(); // Prints full SQL error details
            }
        }
    }// GEN-LAST:event_saveButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_exitButtonActionPerformed

    private void studentNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_studentNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_studentNameActionPerformed

    private void studentfatherTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_studentfatherTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_studentfatherTextFieldActionPerformed

    private void studentcontactTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_studentcontactTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_studentcontactTextFieldActionPerformed

    private void collegenameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_collegenameTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_collegenameTextFieldActionPerformed

    private void studentbranchTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_studentbranchTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_studentbranchTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel collegenameLabel;
    private javax.swing.JTextField collegenameTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField studentName;
    private javax.swing.JLabel studentbranchLabel;
    private javax.swing.JLabel studentbranchLabel1;
    private javax.swing.JTextField studentbranchTextField1;
    private javax.swing.JLabel studentcontactLabel;
    private javax.swing.JTextField studentcontactTextField;
    private javax.swing.JLabel studentfatherLabel;
    private javax.swing.JTextField studentfatherTextField;
    // End of variables declaration//GEN-END:variables
}
