/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.librarymanagement;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Malhotra Computer
 */
public class StudentReport extends javax.swing.JPanel {
    SingletonClass conn = SingletonClass.getInstance();

    /**
     * Creates new form StudentReport
     */
    public StudentReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        overduebooksLabel = new javax.swing.JLabel();
        studentidLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        booksborrowedLabel = new javax.swing.JLabel();
        studentidTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        gradeTextField = new javax.swing.JTextField();
        booksborrowedTextField = new javax.swing.JTextField();
        overduebooksTextField = new javax.swing.JTextField();
        printButton1 = new javax.swing.JButton();

        namePanel.setBackground(new java.awt.Color(0, 0, 51));
        namePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT'S REPORT");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        namePanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 60));

        overduebooksLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        overduebooksLabel.setForeground(new java.awt.Color(255, 255, 255));
        overduebooksLabel.setText("OVERDUE BOOKS");
        namePanel.add(overduebooksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        studentidLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        studentidLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentidLabel.setText("STUDENT ID");
        namePanel.add(studentidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        nameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("NAME");
        namePanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        gradeLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        gradeLabel.setForeground(new java.awt.Color(255, 255, 255));
        gradeLabel.setText("GRADE");
        namePanel.add(gradeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        booksborrowedLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        booksborrowedLabel.setForeground(new java.awt.Color(255, 255, 255));
        booksborrowedLabel.setText("BOOKS BORROWED");
        namePanel.add(booksborrowedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        studentidTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidTextFieldActionPerformed(evt);
            }
        });
        namePanel.add(studentidTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 190, -1));

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        namePanel.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 190, -1));

        gradeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeTextFieldActionPerformed(evt);
            }
        });
        namePanel.add(gradeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 190, -1));

        booksborrowedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksborrowedTextFieldActionPerformed(evt);
            }
        });
        namePanel.add(booksborrowedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 190, -1));

        overduebooksTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overduebooksTextFieldActionPerformed(evt);
            }
        });
        namePanel.add(overduebooksTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 190, -1));

        printButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        printButton1.setText("PRINT");
        printButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButton1ActionPerformed(evt);
            }
        });
        namePanel.add(printButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void studentidTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_studentidTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_studentidTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nameTextFieldActionPerformed

    private void gradeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_gradeTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_gradeTextFieldActionPerformed

    private void booksborrowedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_booksborrowedTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_booksborrowedTextFieldActionPerformed

    private void overduebooksTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_overduebooksTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_overduebooksTextFieldActionPerformed

    private void printButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_printButton1ActionPerformed
        // TODO add your handling code here:
        // if (studentidTextField.getText().isEmpty()) {
        // JOptionPane.showMessageDialog(this, "PLEASE ENTER STUDENT ID");
        // }

        if (nameTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ENTER STUDENT'S NAME");
        } // GEN-LAST:event_printButton1ActionPerformed
        else if (gradeTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ENTER STUDENT GRADE");
        }

        else if (booksborrowedTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ENTER  THE  NAME OF BORROWED BOOK");
        } else if (overduebooksTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ENTER  OVERDUE");
        } else {
            try {
                String studentreport = "INSERT INTO studentreport( name, grade, booksborrowed, overduebooks) VALUES ( ?, ?, ?,?)";

                PreparedStatement ps4 = conn.connection.prepareCall(studentreport);

                // ps4.setString(1, studentidTextField.getText());
                ps4.setString(1, nameTextField.getText());
                ps4.setString(2, gradeTextField.getText());
                ps4.setString(3, booksborrowedTextField.getText());
                ps4.setString(4, overduebooksTextField.getText());

                if (ps4.executeUpdate() > 0) {
                    System.out.println("Data Inserted Successfully");
                    JOptionPane.showMessageDialog(this, "REGISTRATION SUCCESSFUL");
                    // getstudentreport();
                    // Optional: Clear fields

                    // studentidTextField.setText("");
                    nameTextField.setText("");
                    gradeTextField.setText("");
                    booksborrowedTextField.setText("");
                    overduebooksTextField.setText("");
                    // Optional: Navigate to another form
                    // new StudentForm().setVisible(true);

                    // dispose();
                }

            } catch (SQLException ex) {
                ex.printStackTrace(); // Prints full SQL error details
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel booksborrowedLabel;
    private javax.swing.JTextField booksborrowedTextField;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JTextField gradeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel overduebooksLabel;
    private javax.swing.JTextField overduebooksTextField;
    private javax.swing.JButton printButton1;
    private javax.swing.JLabel studentidLabel;
    private javax.swing.JTextField studentidTextField;
    // End of variables declaration//GEN-END:variables
}
